services:
  backend:
    build:
      context: ./Backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
    env_file:
      - ./Backend/.env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
