"""add cascade delete for students when class deleted

Revision ID: 260344a16f9b
Revises: f18d6be023c5
Create Date: 2025-10-10 13:19:50.951892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '260344a16f9b'
down_revision: Union[str, Sequence[str], None] = 'f18d6be023c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('student_class_id_fkey'), 'student', type_='foreignkey')
    # Recreate the foreign key with ON DELETE CASCADE
    op.create_foreign_key(
        op.f('student_class_id_fkey'),
        'student',
        'class',
        ['class_id'],
        ['id'],
        ondelete='CASCADE'
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('student_class_id_fkey'), 'student', type_='foreignkey')

    # Recreate the original foreign key without cascade
    op.create_foreign_key(
        op.f('student_class_id_fkey'),
        'student',
        'class',
        ['class_id'],
        ['id']
    )
    # ### end Alembic commands ###
