"""Updated user model

Revision ID: 91227350ad48
Revises: 0db82a3ef394
Create Date: 2025-09-05 01:48:22.730677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '91227350ad48'
down_revision: Union[str, Sequence[str], None] = '0db82a3ef394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('must_change_password', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'must_change_password')
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###
